-- MySQL Script generated by MySQL Workbench
-- Mon Nov 30 08:03:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema reto5ciclo2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reto5ciclo2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reto5ciclo2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `reto5ciclo2` ;

-- -----------------------------------------------------
-- Table `reto5ciclo2`.`pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto5ciclo2`.`pelicula` (
  `idPelicula` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `resumen` VARCHAR(100) NOT NULL,
  `anoo` YEAR NOT NULL,
  `director` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPelicula`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reto5ciclo2`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto5ciclo2`.`serie` (
  `idSerie` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `temporadas` INT NOT NULL,
  `episodios` INT NOT NULL,
  PRIMARY KEY (`idSerie`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `reto5ciclo2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reto5ciclo2`.`usuario` (
  `id_username` VARCHAR(20) NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
